config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :leads
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lead.rb
class Lead < ApplicationRecord
  validates :name, presence: true
  validates :email_address, presence: true
  validates :telephone_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  def index
    @leads = Lead.all
    if params[:query].present? && !params[:query].empty?
      @leads = @leads.where("name ILIKE ?", "%#{params[:query]}%")
    end
    respond_to do |format|
      format.html
      format.text { render partial: "leads/list", locals: { leads: @leads }, formats: [:html] }
    end
  end

  def show
    @lead = Lead.find(params[:id])
  end

  def new
    @lead = Lead.new
  end

  def create
    @lead = Lead.new(lead_params)
    if @lead.save
      redirect_to lead_path(@lead)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @lead = Lead.find(params[:id])
    if @lead.update(lead_params)
      redirect_to leads_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @lead = Lead.find(params[:id])
    if @lead.destroy
      redirect_to leads_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def lead_params
    params.require(:lead).permit(
      :name,
      :telephone_number,
      :email_address,
      :linked_in,
      :github,
      :follow_up,
      :interview,
      :offer
    )
  end

  def set_lead
    @lead = Lead.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRegister</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/leads/_form.html.erb
<%= simple_form_for(lead) do |f| %>
  <%= f.input :name %>
  <%= f.input :email_address %>
  <%= f.input :telephone_number %>
  <%= f.input :linked_in %>
  <%= f.input :github %>
  <div class="d-flex justify-content-between">
    <div>
      <%= f.submit "Register", class: "btn-red mt-4" %>
    </div>
    <div class="">
      <%= link_to 'Back', root_path, class: 'btn-big mt-4' %>
    </div>
  </div>

<% end %>

app/views/leads/_list.html.erb
<tbody data-search-names-target="list">
  <% leads.sort.each do |lead| %>
    <tr>
      <th scope="row"></th>
      <td class="p-2"><%= lead.name %></td>
      <td class="p-2"><%= lead.email_address %></td>
      <td class="p-2"><%= lead.telephone_number %></td>
      <td class="p-2"><%= link_to(lead.linked_in, lead.linked_in, target: :_blank, class: "table-link") %></td>
      <td class="p-2">
        <% if lead.github? %>
          <%= link_to(lead.github, lead.github, target: :_blank, class: "table-link") %>
        <% end %>
      </td>
      <td><%= link_to '<i class="fa-solid fa-pen-to-square"></i>'.html_safe, edit_lead_path(lead), class: "delete-button" %></td>
      <td><%= link_to '<i class="fas fa-trash"></i>'.html_safe, lead_path(lead), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete-button m-3" %></td>
    </tr>
  <% end %>
</tbody>

app/views/leads/edit.html.erb
<div class="banner">
</div>
<div class="container mb-5">
  <div class="form border p-5">
    <h3>Register Here!</h3>
    <%= render 'form', lead: @lead %>
  </div>
</div>

app/views/leads/index.html.erb
<div class="banner">

</div>
<div class="container mb-5">
  <div class="d-flex justify-content-center"></div>
    <div class="table-card" data-controller="search-names">
      <div class="d-flex justify-content-end m-3 p-3">
        <%= form_with url: leads_path, method: :get, class: "d-flex", data: { search_names_target: "form" } do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control mr-2",
            placeholder: "Type a name",
            data: {
              search_names_target: 'input',
              action: "keyup->search-names#update"
            }
          %>
          <%= submit_tag "Search", name: "", class: "btn-red ms-3" %>
        <% end %>
      </div>
        <div class="table-responsive">
          <table class="table table-striped border rounded">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Tel</th>
                <th scope="col">LinkedIn</th>
                <th scope="col">GitHub</th>
              </tr>
            </thead>
            <%= render "list", leads: @leads %>
          </table>
        </div>
      <div class="m-3 p-3 d-flex justify-content-end">
        <%= link_to 'Add registration', new_lead_path(@lead), class: 'btn-red' %>
      </div>
    </div>
  </div>
</div>

app/views/leads/new.html.erb
<div class="banner">
</div>
<div class="container mb-5">
  <div class="form border p-5">
    <h3>Register Here!</h3>
    <%= render 'form', lead: @lead %>
  </div>
</div>

app/views/leads/show.html.erb
<div class="banner">
  <div class="d-flex justify-content-center">
    <div>
      <h1 class="text-dark">Thanks for registering your details <%= @lead.name %>!</h1>
    </div>
  </div>
  <div class="mt-5 d-flex justify-content-center">
    <div class="mb-3">
      <%= link_to 'Add another registration', new_lead_path(@lead), class: 'btn-red' %>
    </div>
  </div>
</div>
<div class="container mt-5">
  <div class="d-flex justify-content-center">
    <%= image_tag("https://gifrific.com/wp-content/uploads/2014/12/Michael-Jordan-Free-Throw-Dunk-Contest.gif") %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://staticg.sportskeeda.com/editor/2022/02/af653-16442505538786-1920.jpg)">
</div>
<div class="container">
  <div>
    <div class="d-flex justify-content-center">
      <h1 class="overlay border">Welcome to [insert logo here] !</h1>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <div class="mt-5">
      <h3 class='text-white'>Register your details with us and watch your career take flight...</h3>
      <div class="text-white d-flex justify-content-center">
        <h2 class="mt-2"><i class="fa-solid fa-arrow-down fa-bounce"></i></h2>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center mb-5">
    <div>
      <%= link_to 'Click here to register', new_lead_path(@lead), class: 'btn-big' %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%# <%= image_tag "" %>
      <h4 class="text-white">[INSERT LOGO HERE]</h4>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <p><%= link_to "Home", root_path, class: "nav-btn-white me-5" %></p>
          </li>
          <li class="nav-item">
            <p><%= link_to "See all", leads_path, class: "nav-btn me-5" %></p>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-btn me-5" %>
          </li>
          <li class="nav-item dropdown">
          <%# <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "", class: "avatar", alt: "dropdown menu" %>
          <%# </a> %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-btn-white me-5" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>